typography_spectrum: 0.7943424053955823
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.9576775545720011
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0.5
  brandColors: []
  lightness: 0.5
purpose:
  - name: engagement
    url: null
    item: null
favicon: null
name: Seth Zora
analytics:
  twitter: null
  google: null
  facebook: null
